#!/bin/bash

# Define directories
BED_DIR="/rhome/user/CUTRUN_analysis/merged_macs2_output"
OUTPUT_DIR="/rhome/user/CUTRUN_analysis/motif_enrichment"
LOG_DIR="${OUTPUT_DIR}/logs"

# Ensure necessary directories exist
mkdir -p "$LOG_DIR"
mkdir -p "$OUTPUT_DIR"

# Process each BED file in each subdirectory
for bedfile_dir in $BED_DIR/*/; do
    sample_id=$(basename "$bedfile_dir")

    # Assuming there is one .bed file per directory or you need to process all .bed files
    for bed_file in "${bedfile_dir}"*.bed; do
        if [ -f "$bed_file" ]; then  # Ensure it's a file
            bed_basename=$(basename "$bed_file")

            # Create a batch script for each sample and BED file
            BATCH_SCRIPT="/tmp/${sample_id}_${bed_basename}_process.sh"
            cat > "$BATCH_SCRIPT" <<EOL
#!/bin/bash

#SBATCH --job-name=findMotif_${sample_id}
#SBATCH --output=${LOG_DIR}/${sample_id}_%j.log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=24:00:00
#SBATCH --mail-user=email@address
#SBATCH --mail-type=END,FAIL
#SBATCH --partition=intel

export PATH=/rhome/user/tools/homer/bin:$PATH

# Run the motif finding command
findMotifsGenome.pl $bed_file \\
        /rhome/user/mosqt/Aaegy_genome/VectorBase-66_AaegyptiLVP_Genome_chr.fasta \\
        ${OUTPUT_DIR}/${sample_id} \\
        -size 200

EOL

            # Submit the job
            sbatch "$BATCH_SCRIPT"
        fi
    done
done

echo "All jobs have been submitted."
